name: Build and Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Basic build
        run: make GO_BUILDFLAGS='-mod vendor'

      - name: Run checks
        run: make check

      - name: Upload coverage report to Coveralls
        run: |
          GO111MODULE=off go get -u github.com/mattn/goveralls
          goveralls -coverprofile=build/cover.out -service=github
        env:
          COVERALLS_TOKEN: ${{ github.token }}
